#!/bin/bash
#SBATCH --job-name=ridge            # Specify job name
#SBATCH --partition=pq2             # Specify partition name
#SBATCH --time=02:00:00             # Set a limit on the total run time
#SBATCH --account=ppfleiderer       # Charge resources on this project account
#SBATCH --output=log/%j             # Output file
#SBATCH --error=log/%j              # Error file -> write them into the same file

# reuses all command line arguments
# example usage: 
# sbatch slurm_job parallel_script_python_nc.py
python "$@"
